require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "brokkr.gemspec"
    - "spec/**/*.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/Style/OpenStructUse:
  Enabled: false
